# Generated by Django 3.0.12 on 2021-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic_codes', '0002_rename_inserted_at_created_at'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='sic_codes',
            field=models.ManyToManyField(related_name='company_sic_codes', to='sic_codes.Code', verbose_name='SIC codes'),
        ),
        migrations.DeleteModel(
            name='CompanySICCodes',
        ),
    ]
