# Generated by Django 3.1.7 on 2021-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_sic_codes_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
