# Generated by Django 3.1.7 on 2021-03-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0014_add_categories_m2m'),
        ('companies', '0003_make_address_etc_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jurisdictions',
            field=models.ManyToManyField(related_name='jurisdictions', to='regulations.Jurisdiction'),
        ),
    ]
