# Generated by Django 3.1.7 on 2021-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_jurisdictions_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-10', '3-10'), ('11-100', '11-100'), ('100+', '100+')], db_index=True, default='1-2', max_length=20),
        ),
    ]
