# Generated by Django 3.1.7 on 2021-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_number_of_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
        migrations.AddField(
            model_name='company',
            name='full_time_contract_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Full-time contract employees'),
        ),
        migrations.AddField(
            model_name='company',
            name='full_time_permanent_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Full-time permanent employees'),
        ),
        migrations.AddField(
            model_name='company',
            name='part_time_contract_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Part-time contract employees'),
        ),
        migrations.AddField(
            model_name='company',
            name='part_time_permanent_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Part-time permanent employees'),
        ),
    ]
