# Generated by Django 3.0.12 on 2021-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sic_codes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regulator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Short name")),
                ("verbose_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("url", models.URLField(verbose_name="URL")),
                ("description", models.TextField(blank=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sic_codes",
                    models.ManyToManyField(
                        related_name="sic_codes",
                        to="sic_codes.Code",
                        verbose_name="SIC codes",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
