# Generated by Django 3.0.12 on 2021-02-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic_codes', '0001_initial'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('is_blanket', models.BooleanField(db_index=True, verbose_name='is blanket?')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sic_codes', models.ManyToManyField(related_name='regulation_sic_codes', to='sic_codes.Code', verbose_name='SIC codes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='regulator',
            name='sic_codes',
            field=models.ManyToManyField(related_name='regulator_sic_codes', to='sic_codes.Code', verbose_name='SIC codes'),
        ),
        migrations.CreateModel(
            name='RegulatorRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regulations.Regulation')),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulator_regulations', to='regulations.Regulator')),
            ],
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='regulator',
            name='regulations',
            field=models.ManyToManyField(blank=True, related_name='regulators', through='regulations.RegulatorRegulation', to='regulations.Regulation'),
        ),
    ]
