# Generated by Django 3.0.12 on 2021-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_change_descriptions_to_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='is_blanket',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is blanket?'),
        ),
    ]
