# Generated by Django 3.0.12 on 2021-02-09 10:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_add_is_blanket_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_regulations', to='regulations.Regulation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.CategoryTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='regulation',
            name='categories',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of categories.', through='regulations.RegulationCategory', to='regulations.CategoryTag', verbose_name='Categories'),
        ),
    ]
