# Generated by Django 3.1.6 on 2021-02-12 12:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_rename_inserted_at_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytag',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='categorytag',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='categories',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of categories.', related_name='regulations', through='regulations.RegulationCategory', to='regulations.CategoryTag', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='regulationcategory',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_categories', to='regulations.regulation'),
        ),
        migrations.AlterField(
            model_name='regulationcategory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_categories', to='regulations.categorytag'),
        ),
    ]
