# Generated by Django 3.1.6 on 2021-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_add_verbose_name_and_description_to_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Mandatory'), (1, 'Best practice'), (2, 'Optional')], db_index=True, default=0),
        ),
    ]
