# Generated by Django 3.1.7 on 2021-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0009_add_jurisdiction_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulator',
            name='regulations',
        ),
        migrations.AddField(
            model_name='regulation',
            name='regulators',
            field=models.ManyToManyField(blank=True, related_name='regulations', to='regulations.Regulator'),
        ),
        migrations.DeleteModel(
            name='RegulatorRegulation',
        ),
    ]
