# Generated by Django 3.1.7 on 2021-03-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0010_change_regulator_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulationjurisdiction',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='regulationjurisdiction',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='jurisdictions',
        ),
        migrations.DeleteModel(
            name='JurisdictionTag',
        ),
        migrations.DeleteModel(
            name='RegulationJurisdiction',
        ),
    ]
