# Generated by Django 3.1.7 on 2021-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic_codes', '0002_rename_inserted_at_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
