# Generated by Django 3.0.12 on 2021-02-05 17:19

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('regulations', '0002_create_regulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trackers', to='companies.Company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Complete'), (3, 'Due'), (4, 'Overdue')], db_index=True, default=0)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='regulations.Regulation')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.Tracker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Complete'), (3, 'Due'), (4, 'Overdue')], db_index=True, default=0)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tracker.Task')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
