# Generated by Django 3.0.12 on 2021-02-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_inserted_at_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='step',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tracker',
        ),
    ]
