# Generated by Django 3.0.12 on 2021-02-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_rename_inserted_at_created_at'),
        ('tracker', '0003_remove_tracker_from_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_regulations', to='regulations.Regulation')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_regulations', to='tracker.Tracker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='tracker',
            name='regulations',
            field=models.ManyToManyField(related_name='trackers', through='tracker.TrackerRegulation', to='regulations.Regulation'),
        ),
    ]
