# Generated by Django 3.0.12 on 2021-02-09 15:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_regulations_to_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Complete'), (3, 'Due'), (4, 'Overdue')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.Task')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_tasks', to='tracker.Tracker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Complete'), (3, 'Due'), (4, 'Overdue')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tracker.Step')),
                ('tracked_task', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_steps', to='tracker.TrackedTask')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
