# Generated by Django 3.1.6 on 2021-02-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_create_tracked_task_and_tracked_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_tasks', to='tracker.task'),
        ),
    ]
