# Generated by Django 3.1.6 on 2021-02-16 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0007_add_user_to_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
